### ISSUE TITLE
前端---如果这个标签太长了，要不要显示省略号嘞

### ISSUE THREAD

**Issue by YuliNet** [pkussoj/OnlineJudge_BasedOnQDU#13]
![image](https://user-images.githubusercontent.com/20679637/85190880-3b4c3780-b2ef-11ea-9467-26317eb5839b.png)

[problem页面](http://124.70.30.114/problem)

**Comment by lanweipeng** [comment]
我这里想了两种方案，一种是标签超出省略，然后鼠标放上去给个提示显示全部，一种是输入时限制输入大小
![image](https://user-images.githubusercontent.com/41134448/85191606-14dbcb80-b2f2-11ea-9de3-ccd65c9c8c30.png)
@需求组给个意见
